import{state}from"./state.js";
import{mountWriting}from"./writing-page.js";
import{loadProgress,saveSettings,summary,card,update,reset,exportData,importData,introduce,recordSkill,recordLessonCheck,mastery}from"./progress.js";
import{dueItems,newItems,rate,sessionItems,currentLesson,unlockedLessons,lessonMastered,lessonReady}from"./scheduler.js";
import{playChinese,stopAudio,available as audioAvailable,voicesReady}from"./audio.js";import*as writing from"./writing.js";
import{exampleWords}from"./examples.js";
const app=document.querySelector("#app"),toast=document.querySelector("#toast"),nav=document.querySelector("#nav");let activeSession;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const button=(text,href,cls="")=>`<a class="button ${cls}" href="${href}">${text}</a>`;
const progressBar=(value,max,label="Fortschritt")=>`<div class="progress" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${max?Math.round(value/max*100):0}%"></span></div>`;
function notify(text){toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
async function boot(){try{const[v,c,l]=await Promise.all([fetch("data/course.json").then(ok),fetch("data/characters.json").then(ok),fetch("data/lessons.json").then(ok)]);state.vocabulary=v.items;state.characters=Object.fromEntries(c.characters.map(x=>[x.character,x]));state.lessons=l;loadProgress();addEvents();route();if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("service-worker.js").catch(()=>{})}catch(e){app.innerHTML=`<section class="panel"><h1>Die App konnte nicht geladen werden</h1><p>${esc(e.message)}</p></section>`}}
function ok(r){if(!r.ok)throw Error(`Datei nicht gefunden (${r.status})`);return r.json()}
function addEvents(){window.addEventListener("hashchange",route);window.addEventListener("pagehide",stopAudio);document.addEventListener("audioerror",audioError);document.querySelector("#menu-button").onclick=e=>{const open=nav.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",open)};app.addEventListener("click",click);app.addEventListener("submit",submit);app.addEventListener("input",input);app.addEventListener("change",change)}
function audioError(e){notify(e.detail.reason==="disabled"?"Audio ist in den Einstellungen deaktiviert.":e.detail.reason==="unsupported"?"Dieses Gerät bietet keine Sprachausgabe an.":e.detail.reason==="novoice"?"Keine chinesische Systemstimme gefunden. Siehe Einstellungen.":e.detail.reason==="blocked"?"Die Wiedergabe wurde blockiert. Tippe erneut auf Anhören.":"Die Aussprache konnte nicht wiedergegeben werden.")}
function route(){stopAudio();writing.destroy();nav.classList.remove("open");const path=(location.hash.slice(1)||"/").split("?")[0];document.querySelectorAll("nav a").forEach(a=>a.toggleAttribute("aria-current",a.hash.slice(1)===path));if(path==="/")home();else if(["/learn","/review","/practice","/new"].includes(path))startSession(path.slice(1));else if(path.startsWith("/check/"))lessonCheck(path.split("/").pop());else if(path==="/write")writeView();else if(path==="/vocabulary")vocabulary();else if(path.startsWith("/word/"))detail(path.split("/").pop());else if(path==="/progress")progressView();else if(path==="/settings")settingsView();else if(path==="/sources")sources();else home();window.scrollTo(0,0)}
function home(){const s=summary(),due=dueItems().length,fresh=newItems().length,lesson=currentLesson(),free=!due&&!fresh&&s.started;app.innerHTML=`<section class="hero"><div class="panel"><p class="eyebrow">${lesson?esc(lesson.title):"Kurs abgeschlossen"}</p><h1>${lesson?esc(lesson.canDo):"Alle Kursziele erreicht."}</h1><p class="muted">${lesson?esc(lesson.objective):"Wiederhole regelmäßig."}</p>${progressBar(s.started,state.vocabulary.length,"Begonnener Wortschatz")}<p>${s.started} von ${state.vocabulary.length} Wörtern begonnen</p>${free?'<p class="feedback">Für heute ist alles geplant erledigt. Du kannst trotzdem frei weiterüben.</p>':""}<div class="actions">${button(free?"Frei weiterüben":"Weiterlernen",free?"#/practice":"#/learn")}${button(`Wiederholen (${due})`,"#/review","secondary")}${button("Mehr neue Wörter","#/new","secondary")}${button("Schreiben üben","#/write","secondary")}</div></div><aside class="panel"><h2>Heute</h2><p class="muted">Fälliges zuerst wiederholen. Neue Wörter kommen in kleinen Portionen – du kannst jederzeit eine weitere starten. Erfolgreiche Abrufe werden über mehrere Tage verteilt.</p><div class="stats"><div class="stat"><strong>${due}</strong>fällig</div><div class="stat"><strong>${fresh}</strong>neu</div><div class="stat"><strong>${s.learned}</strong>abrufbar</div><div class="stat"><strong>${s.mature}</strong>gefestigt</div></div></aside></section><section class="lesson-list"><h2>Lernweg</h2>${state.lessons.map(lessonCard).join("")}</section><section class="actions">${button("Wortschatz","#/vocabulary","secondary")}${button("Fortschritt","#/progress","secondary")}${button("Quellen & Lizenzen","#/sources","secondary")}</section>`}
function lessonCard(l){const open=unlockedLessons().some(x=>x.id===l.id),done=lessonMastered(l),ready=lessonReady(l),n=l.items.filter(id=>mastery(card(id))>=2).length;return`<article class="panel lesson ${open?"":"locked"}"><p class="eyebrow">${done?"✓ gemeistert":ready?"Transfercheck bereit":open?"Verfügbar":"🔒 gesperrt"}</p><h3>${esc(l.title)}</h3><p>${esc(l.canDo)}</p>${progressBar(n,l.items.length,l.title)}<small>${n}/${l.items.length} an mindestens zwei Tagen in Hören, Bedeutung und Abruf bestätigt</small>${ready&&!done?`<div class="actions">${button("Können zeigen",`#/check/${l.id}`)}</div>`:""}</article>`}
function startSession(mode){const items=sessionItems(mode);if(!items.length){app.innerHTML=`<section class="panel"><h1>Nichts fällig</h1><p>${mode==="new"?"Alle Wörter wurden bereits eingeführt.":"Für heute sind alle Wiederholungen geschafft. Die nächsten erscheinen an ihrem geplanten Tag."}</p><div class="actions">${button("Mehr neue Wörter","#/new")}${button("Frei weiterüben","#/practice","secondary")}${button("Zur Startseite","#/","secondary")}</div></section>`;return}activeSession={mode,queue:items.map(v=>({v})),index:0,attempts:0,correct:0,retries:{}};renderExercise()}
function renderExercise(){const s=activeSession;if(s.index>=s.queue.length){app.innerHTML=`<section class="panel"><p class="eyebrow">Sitzung beendet</p><h1>Aktiv geübt</h1><div class="stats"><div class="stat"><strong>${s.attempts}</strong>Abrufe</div><div class="stat"><strong>${s.correct}</strong>korrekt</div></div><p>Fehlerhafte Wörter werden höchstens zweimal zusätzlich geübt und morgen erneut eingeplant. Weitere Übung heute verlängert die Wiederholungsabstände nicht.</p><div class="actions">${button("Zur Startseite","#/")}<button data-session="new">Mehr neue Wörter</button><button data-session="practice" class="secondary">Frei weiterüben</button></div></section>`;return}const v=s.queue[s.index].v,c=card(v.id);s.current=v;s.answered=false;if(!c.seen&&!c.n){introduce(v.id);s.queue.splice(Math.min(s.queue.length,s.index+3),0,{v,retrieval:true});return renderIntro(v)}const skill=weakestSkill(c),type=exerciseType(c,skill,v);s.skill=type==="sentence"?"sentence":skill;s.type=type;if(type==="meaning")renderTypedMeaning(v);else if(type==="production")renderProduction(v);else if(type==="tone")renderTone(v);else if(type==="sentence")renderSentence(v);else renderListening(v)}
function weakestSkill(c){return["meaning","production","listening"].sort((a,b)=>c.skills[a]-c.skills[b])[0]}
function exerciseType(c,skill,v){if(Math.min(c.skills.meaning,c.skills.production,c.skills.listening)>=2&&c.n%4===3)return"sentence";if(skill==="listening")return c.n%2&&v.pinyinNumbered.match(/[1-5]/g)?.length===1?"tone":"listening";return skill}
function header(label){const s=activeSession;return`<p class="eyebrow">${s.mode==="practice"?"Freies Üben · ":""}${label} · ${s.index+1}/${s.queue.length}</p>${progressBar(s.index,s.queue.length)}`}
function pinyin(v,where){const show=where==="intro"||state.settings.pinyin==="immer"||(state.settings.pinyin==="progressiv"&&mastery(card(v.id))<2)||where==="answer";return show?`<div class="pinyin">${v.pinyin}</div>`:where==="question"?`<button type="button" class="secondary pinyin-reveal" data-reveal-pinyin="${esc(v.pinyin)}">Pinyin zeigen</button>`:""}
function renderIntro(v){app.innerHTML=`<section class="card learn-card">${header("Neues Wort")}<div class="hanzi" lang="zh-Hans">${v.simplified}</div>${pinyin(v,"intro")}<div class="meaning">${esc(v.shortGerman)}</div><button data-audio="${v.simplified}">▶ Aussprache</button><p>${esc(v.noteGerman)}</p>${example(v)}<div class="feedback"><strong>Merke:</strong> Gleich musst du das Wort selbst abrufen.</div><div class="actions"><button data-continue>Weiter</button></div></section>`;if(state.settings.autoAudio)playChinese(v.simplified)}
function renderTypedMeaning(v){app.innerHTML=`<section class="card learn-card">${header("Bedeutung aktiv abrufen")}<div class="hanzi" lang="zh-Hans">${v.simplified}</div>${pinyin(v,"question")}<form data-response="meaning"><label for="response">Was bedeutet das?</label><input name="response" id="response" class="response" autocomplete="off" required><button>Prüfen</button></form><div id="feedback" aria-live="polite"></div></section>`;requestAnimationFrame(()=>document.querySelector("#response")?.focus())}
function renderProduction(v){app.innerHTML=`<section class="card learn-card">${header("Chinesisch aktiv abrufen")}<div class="meaning">${esc(v.shortGerman)}</div><p>Sprich die Form zuerst und gib danach Hanzi, Pinyin mit Tonzeichen oder nummeriertes Pinyin ein.</p><form data-response="production"><label for="response">Chinesische Form</label><input name="response" id="response" class="response" autocomplete="off" required><button>Prüfen</button></form><div id="feedback" aria-live="polite"></div></section>`;requestAnimationFrame(()=>document.querySelector("#response")?.focus())}
function renderListening(v){const answers=choices(v,"semantic");app.innerHTML=`<section class="card learn-card">${header("Hörverstehen")}<p class="prompt">Höre zu. Welche Bedeutung passt?</p><button data-audio="${v.simplified}">▶ Noch einmal anhören</button><div class="answer-grid">${answers.map(a=>`<button class="answer" data-answer="${a.id}">${esc(a.shortGerman)}</button>`).join("")}</div><div id="feedback" aria-live="polite"></div></section>`;playChinese(v.simplified)}
function renderTone(v){const opts=toneChoices(v);app.innerHTML=`<section class="card learn-card">${header("Töne unterscheiden")}<p class="prompt">Höre zu. Welchen lexikalischen Ton hat die erste Silbe?</p><button data-audio="${v.simplified}">▶ Noch einmal anhören</button><div class="answer-grid">${opts.map(x=>`<button class="answer" data-tone="${x.value}">${esc(x.label)}</button>`).join("")}</div><p class="meta">Tonveränderungen im natürlichen Sprechen werden nach der Antwort erklärt.</p><div id="feedback" aria-live="polite"></div></section>`;playChinese(v.simplified)}
function renderSentence(v){const ex=v.examples[0];app.innerHTML=`<section class="card learn-card">${header("Im Satz anwenden")}<p class="prompt">Übertrage den ganzen Satz ins Chinesische.</p><p>${esc(ex.de)}</p><form data-response="sentence"><label for="response">Chinesischer Satz</label><input name="response" id="response" class="response" autocomplete="off" required><button>Prüfen</button></form><div id="feedback" aria-live="polite"></div></section>`;requestAnimationFrame(()=>document.querySelector("#response")?.focus())}
function choices(v,kind){const c=card(v.id),known=new Set([...Object.keys(state.progress.c),...unlockedLessons().flatMap(l=>l.items)]),pool=state.vocabulary.filter(x=>x.id!==v.id&&known.has(x.id));pool.sort((a,b)=>(c.confusions[b.id]||0)-(c.confusions[a.id]||0)+similarity(v,b,kind)-similarity(v,a,kind));return shuffle([v,...pool.slice(0,3)])}
function similarity(a,b,kind){let n=0;if(a.tags.some(t=>b.tags.includes(t)))n+=3;if(a.partOfSpeech===b.partOfSpeech)n+=2;if(kind==="form"&&a.simplified.length===b.simplified.length)n+=2;if(a.pinyin.split(" ").length===b.pinyin.split(" ").length)n++;return n}
function shuffle(xs){return xs.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function toneChoices(v){const tone=Number(v.pinyinNumbered.match(/[1-5]/)?.[0]||5),labels=[1,2,3,4,5].map(n=>({value:String(n),label:n===5?"neutraler Ton":`${n}. Ton`}));return shuffle([labels[tone-1],...shuffle(labels.filter(x=>x.value!==String(tone))).slice(0,3)])}
function answer(id,el){finishChoice(id===activeSession.current.id,el,id)}
function toneAnswer(value,el){const correct=activeSession.current.pinyinNumbered.match(/[1-5]/)?.[0]||"5";finishChoice(value===correct,el,value)}
function finishChoice(good,el,chosen){if(activeSession.answered)return;activeSession.answered=true;el.classList.add(good?"correct":"wrong");app.querySelectorAll("[data-answer],[data-tone]").forEach(b=>b.disabled=true);recordResult(good,chosen);showFeedback(good)}
function diagnostic(v,chosen){if(!chosen)return"Vergleiche Form, Bedeutung und Ton noch einmal bewusst.";const other=state.vocabulary.find(x=>x.id===chosen);if(other?.pinyin===v.pinyin)return`${other.simplified} und ${v.simplified} klingen gleich, unterscheiden sich aber in Schrift oder Gebrauch.`;if(other?.tags.some(t=>v.tags.includes(t)))return`Beide Antworten gehören zum selben Themenfeld. Achte auf die genaue Funktion: ${v.noteGerman}`;if(activeSession.type==="tone")return`Gesucht war der lexikalische Ton der ersten Silbe. Kontextbedingte Tonänderungen können beim Anhören anders klingen.`;return`Deine Antwort passt hier nicht zur gefragten Bedeutung oder Form.`}
function showFeedback(good,ratePronunciation=false){const v=activeSession.current,f=document.querySelector("#feedback");f.innerHTML=`<div class="feedback"><strong>${good?"✓ Richtig.":"✕ Noch nicht sicher."}</strong>${good?"":`<p>${esc(diagnostic(v,activeSession.chosen))}</p>`}<p><span lang="zh-Hans">${v.simplified}</span></p>${pinyin(v,"answer")}<p>${esc(v.shortGerman)} · ${esc(v.noteGerman)}</p>${example(v)}<button data-audio="${esc(v.simplified)}">▶ Wort anhören und nachsprechen</button>${ratePronunciation?`<p>Die Systemstimme ist nur ein Modell. Vergleiche Rhythmus und Töne ehrlich; Schrift und Aussprache werden getrennt gewertet.</p><div class="rating"><button data-pronunciation="again">Noch üben</button><button data-pronunciation="good" class="secondary">Klang passend</button></div>`:`<div class="actions"><button data-next data-result="${good?"good":"again"}">Weiter</button></div>`}</div>`}
function example(v){const ex=v.examples[0],words=exampleWords(ex,state.vocabulary);return`<div class="example"><div class="example-header"><strong class="example-sentence" lang="zh-Hans">${esc(ex.zh)}</strong><button class="secondary example-audio" type="button" data-audio="${esc(ex.zh)}" aria-label="Ganzen Beispielsatz anhören">▶ Satz anhören</button></div><div class="example-pinyin">${esc(ex.pinyin)}</div><p class="example-translation">${esc(ex.de)}</p><div class="word-breakdown" aria-label="Wörter im Beispielsatz">${words.map(word=>`<div class="word-gloss"><strong lang="zh-Hans">${esc(word.text)}</strong><span>${esc(word.pinyin)}</span><small>${esc(word.de)}</small></div>`).join("")}</div></div>`}
function recordResult(good,chosen=""){const s=activeSession;s.chosen=chosen;s.attempts++;if(good)s.correct++;recordSkill(s.current.id,s.skill,good,good?"":chosen);if(!good&&(s.retries[s.current.id]||0)<2){s.retries[s.current.id]=(s.retries[s.current.id]||0)+1;s.queue.splice(Math.min(s.queue.length,s.index+3),0,{v:s.current,retry:true})}}
function advance(rating){rate(activeSession.current.id,rating);activeSession.index++;renderExercise()}
function submit(e){const kind=e.target.dataset.response;if(!kind)return;e.preventDefault();if(kind==="lesson-check")return submitLessonCheck(e);if(activeSession.answered)return;const value=new FormData(e.target).get("response")||"",good=kind==="meaning"?acceptedMeaning(activeSession.current,value):kind==="sentence"?acceptedSentence(activeSession.current,value):acceptedProduction(activeSession.current,value);activeSession.answered=true;activeSession.baseResult=good;e.target.querySelectorAll("input,button").forEach(x=>x.disabled=true);recordResult(good,value);showFeedback(good,kind==="production")}
function acceptedMeaning(v,value){const norm=s=>s.toLowerCase().trim().replace(/[!?.,;…]/g,"").replace(/\b(der|die|das|ein|eine)\b/g,"").replace(/\s+/g," ").trim();return v.german.some(x=>norm(value)===norm(x))||norm(v.shortGerman).split(/\s*[\/;]\s*/).includes(norm(value))}
function acceptedProduction(v,value){const norm=s=>s.toLowerCase().replace(/[\s'’.-]/g,"").normalize("NFC");return[norm(v.simplified),norm(v.traditional),norm(v.pinyin),norm(v.pinyinNumbered)].includes(norm(value))}
function acceptedSentence(v,value){const ex=v.examples[0],norm=s=>s.toLowerCase().replace(/[\s'’.,!?。！？-]/g,"").normalize("NFC");return[norm(ex.zh),norm(ex.pinyin)].includes(norm(value))}
function lessonCheck(id){const l=state.lessons.find(x=>x.id===id);if(!l||!lessonReady(l))return home();app.innerHTML=`<section class="card learn-card"><p class="eyebrow">Transfercheck · ${esc(l.title)}</p><h1>${esc(l.canDo)}</h1><p class="prompt">${esc(l.check.prompt)}</p><p class="muted">Keine Auswahlantwort: Formuliere selbst in Hanzi oder Pinyin.</p><form data-response="lesson-check" data-lesson="${l.id}"><label for="response">Deine Antwort</label><input name="response" id="response" class="response" autocomplete="off" required><button>Prüfen</button></form><div id="feedback" aria-live="polite"></div></section>`;requestAnimationFrame(()=>document.querySelector("#response")?.focus())}
function submitLessonCheck(e){const l=state.lessons.find(x=>x.id===e.target.dataset.lesson),value=new FormData(e.target).get("response")||"",norm=s=>s.toLowerCase().replace(/[\s'’.,!?。！？-]/g,"").normalize("NFC"),good=l.check.accepted.some(x=>norm(x)===norm(value));e.target.querySelectorAll("input,button").forEach(x=>x.disabled=true);if(good)recordLessonCheck(l.id,true);document.querySelector("#feedback").innerHTML=`<div class="feedback"><strong>${good?"✓ Lernziel gezeigt.":"Noch nicht ganz."}</strong><p lang="zh-Hans">${esc(l.check.model)}</p><div class="pinyin">${esc(l.check.pinyin)}</div><p>${esc(l.check.explanation)}</p><div class="actions">${good?button("Weiter zum Lernweg","#/"):`<button data-retry-check="${l.id}">Noch einmal versuchen</button>`}</div></div>`}
function pronunciationRate(r){recordSkill(activeSession.current.id,"pronunciation",r==="good");advance(activeSession.baseResult?(r==="good"?"good":"hard"):"again")}
function vocabulary(query=""){const q=query.trim().toLowerCase(),items=state.vocabulary.filter(v=>!q||[v.simplified,v.traditional,v.pinyin,v.shortGerman].join(" ").toLowerCase().includes(q));app.innerHTML=`<section><p class="eyebrow">Alle Einträge</p><h1>Wortschatz</h1><input class="search" id="vocab-search" type="search" placeholder="Chinesisch, Pinyin oder Deutsch suchen" value="${esc(query)}"><div class="list" id="vocab-list">${vocabRows(items)}</div></section>`}
function vocabRows(items){return items.map(v=>`<a class="vocab-row" href="#/word/${v.id}"><span class="zh" lang="zh-Hans">${v.simplified}</span><span>${v.pinyin}</span><span class="de">${esc(v.shortGerman)}</span><span class="meta">${mastery(card(v.id))}/9</span></a>`).join("")||"<p>Keine Treffer.</p>"}
function detail(id){const v=state.vocabulary.find(x=>x.id===id);if(!v)return home();app.innerHTML=`<article class="panel"><p class="eyebrow">Wortdetails · Gesamtkompetenz ${mastery(card(id))}/9</p><div class="hanzi" lang="zh-Hans">${v.simplified}</div>${pinyin(v,"answer")}<h1>${esc(v.shortGerman)}</h1><button data-audio="${v.simplified}">▶ Aussprache</button><h2>Bedeutung und Gebrauch</h2><p>${esc(v.noteGerman)}</p><p class="meta">${esc(v.partOfSpeech)}</p><h2>Beispiel</h2>${example(v)}<h2>Zeichen</h2><p>${v.characters.map(c=>`<a class="button secondary" href="#/write?char=${encodeURIComponent(c)}">${c}</a>`).join(" ")}</p></article>`}
function writeView(){mountWriting(new URLSearchParams(location.hash.split("?")[1]||"").get("char"))}
function progressView(){const s=summary(),cards=Object.keys(state.progress.c).map(card),avg=skill=>cards.length?Math.round(cards.reduce((n,c)=>n+c.skills[skill],0)/cards.length*10)/10:0;app.innerHTML=`<section><p class="eyebrow">Dein Lernstand</p><h1>Fortschritt nach Kompetenz</h1><div class="stats"><div class="stat"><strong>${s.started}/${state.vocabulary.length}</strong>begonnen</div><div class="stat"><strong>${s.learned}</strong>aktiv abrufbar</div><div class="stat"><strong>${s.mature}</strong>gefestigt</div><div class="stat"><strong>${s.due}</strong>heute fällig</div></div><section class="panel competency"><h2>Kompetenzprofil</h2>${["meaning","production","listening","sentence","pronunciation","writing"].map(k=>`<div><span>${{meaning:"Bedeutung",production:"Aktiver Abruf",listening:"Hören",sentence:"Satztransfer",pronunciation:"Aussprache",writing:"Schreiben"}[k]}</span>${progressBar(avg(k),9,k)}<strong>${avg(k)}/9</strong></div>`).join("")}</section><p class="muted">Ein Wort gilt erst als abrufbar, wenn Bedeutung, aktiver Abruf und Hören an mindestens zwei verschiedenen Tagen gelangen. Der Transfercheck prüft danach das Lernziel. Aussprache ist eine ehrliche Selbsteinschätzung; Schreiben bleibt optional.</p></section>`}
function settingsView(){app.innerHTML=`<section class="panel"><p class="eyebrow">Persönliche Auswahl</p><h1>Einstellungen</h1><form class="settings-form" id="settings"><label class="field"><span>Aussprache aktivieren</span><input name="audio" type="checkbox" ${state.settings.audio?"checked":""}></label><label class="field"><span>Neue Wörter automatisch vorsprechen</span><input name="autoAudio" type="checkbox" ${state.settings.autoAudio?"checked":""}></label><label class="field"><span>Pinyin</span><select name="pinyin"><option value="progressiv" ${state.settings.pinyin==="progressiv"?"selected":""}>Mit wachsender Sicherheit ausblenden</option><option value="immer" ${state.settings.pinyin==="immer"?"selected":""}>Immer zeigen</option><option value="antwort" ${state.settings.pinyin==="antwort"?"selected":""}>Erst nach der Antwort</option></select></label><label class="field"><span>Neue Wörter pro Lernportion (beliebig oft starten)</span><input name="dailyNew" type="number" min="1" max="20" value="${state.settings.dailyNew}"></label></form><h2>Sicherung</h2><div class="actions"><button data-export>Fortschritt exportieren</button><label class="button secondary">Fortschritt importieren<input id="import" type="file" accept="application/json" hidden></label><button data-reset class="danger">Fortschritt zurücksetzen</button></div><div id="audio-status">${audioHint()}</div><p class="meta">Die Aussprache nutzt die chinesische Stimme des Geräts. Höre zusätzlich regelmäßig Muttersprachlern zu.</p></section>`;voicesReady().then(()=>{const box=document.querySelector("#audio-status");if(box)box.innerHTML=audioHint()})}
const audioHint=()=>audioAvailable()?"":'<p class="feedback">Auf diesem Gerät ist keine chinesische Sprachausgabe installiert, deshalb bleibt die Aussprache stumm. Richte eine chinesische Systemstimme ein (Linux: speech-dispatcher mit espeak-ng; Windows und macOS: chinesische Stimme in den Sprachausgabe-Einstellungen nachinstallieren) und lade die Seite neu.</p>';
function sources(){app.innerHTML=`<article class="panel"><p class="eyebrow">Transparenz</p><h1>Quellen & Lizenzen</h1><p>Datensatzversion 2026-08-24 · App-Version 3.0.0</p><ul class="source-list"><li><strong>HanDeDict</strong> – deutsche Kernbedeutungen.</li><li><strong>CC-CEDICT</strong> – Schriftform, Pinyin und Bedeutungsumfang.</li><li><strong>Hanzi Writer</strong> – Strichfolge und Schreibquiz.</li></ul><p>Aussprache wird lokal durch die chinesische Systemstimme synthetisiert und ist keine kuratierte Muttersprachleraufnahme. Sie dient als Modell, nicht als alleinige Aussprachebewertung.</p><p>Vollständige Hinweise stehen in <a href="LICENSES.md">LICENSES.md</a>.</p></article>`}
function click(e){const b=e.target.closest("button");if(!b)return;if(b.dataset.session)startSession(b.dataset.session);else if(b.dataset.audio)playChinese(b.dataset.audio);else if(b.dataset.revealPinyin){b.outerHTML=`<div class="pinyin">${esc(b.dataset.revealPinyin)}</div>`}else if(b.dataset.retryCheck)lessonCheck(b.dataset.retryCheck);else if(b.dataset.answer)answer(b.dataset.answer,b);else if(b.dataset.tone)toneAnswer(b.dataset.tone,b);else if(b.hasAttribute("data-continue")){activeSession.index++;renderExercise()}else if(b.hasAttribute("data-next"))advance(b.dataset.result);else if(b.dataset.pronunciation)pronunciationRate(b.dataset.pronunciation);else if(b.hasAttribute("data-export")){const blob=new Blob([JSON.stringify(exportData(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`chinesisch-fortschritt-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}else if(b.hasAttribute("data-reset")&&confirm("Den gesamten Lernfortschritt wirklich zurücksetzen?")){reset();notify("Fortschritt zurückgesetzt.");settingsView()}}
function input(e){if(e.target.id==="vocab-search")document.querySelector("#vocab-list").innerHTML=vocabRows(state.vocabulary.filter(v=>[v.simplified,v.traditional,v.pinyin,v.shortGerman].join(" ").toLowerCase().includes(e.target.value.toLowerCase())))}
async function change(e){if(e.target.closest("#settings")){const f=new FormData(e.target.form);state.settings.audio=f.has("audio");state.settings.autoAudio=f.has("autoAudio");state.settings.pinyin=f.get("pinyin");state.settings.dailyNew=Math.max(1,Math.min(20,Number(f.get("dailyNew"))||5));saveSettings();notify("Einstellungen gespeichert.")}if(e.target.id==="import"&&e.target.files[0])try{importData(JSON.parse(await e.target.files[0].text()));notify("Fortschritt importiert.");settingsView()}catch(err){notify(`Import fehlgeschlagen: ${err.message}`)}}
boot();
