import{state}from"./state.js";
import{loadProgress,saveSettings,summary,card,update,reset,exportData,importData,introduce,recordSkill,mastery}from"./progress.js";
import{dueItems,newItems,rate,sessionItems,currentLesson,unlockedLessons,lessonMastered}from"./scheduler.js";
import{playChinese,stopAudio,available as audioAvailable}from"./audio.js";import*as writing from"./writing.js";
const app=document.querySelector("#app"),toast=document.querySelector("#toast"),nav=document.querySelector("#nav");let activeSession,writeIndex=0,writeMode="watch";
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const button=(text,href,cls="")=>`<a class="button ${cls}" href="${href}">${text}</a>`;
const progressBar=(value,max,label="Fortschritt")=>`<div class="progress" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${max?Math.round(value/max*100):0}%"></span></div>`;
function notify(text){toast.textContent=text;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
async function boot(){try{const[v,c,l]=await Promise.all([fetch("data/vocabulary.json").then(ok),fetch("data/characters.json").then(ok),fetch("data/lessons.json").then(ok)]);state.vocabulary=v.items;state.characters=Object.fromEntries(c.characters.map(x=>[x.character,x]));state.lessons=l;loadProgress();addEvents();route();if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("service-worker.js").catch(()=>{})}catch(e){app.innerHTML=`<section class="panel"><h1>Die App konnte nicht geladen werden</h1><p>${esc(e.message)}</p></section>`}}
function ok(r){if(!r.ok)throw Error(`Datei nicht gefunden (${r.status})`);return r.json()}
function addEvents(){window.addEventListener("hashchange",route);window.addEventListener("pagehide",stopAudio);document.addEventListener("audioerror",audioError);document.querySelector("#menu-button").onclick=e=>{const open=nav.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",open)};app.addEventListener("click",click);app.addEventListener("submit",submit);app.addEventListener("input",input);app.addEventListener("change",change)}
function audioError(e){notify(e.detail.reason==="disabled"?"Audio ist in den Einstellungen deaktiviert.":e.detail.reason==="unsupported"?"Dieses Gerät bietet keine Sprachausgabe an.":e.detail.reason==="blocked"?"Die Wiedergabe wurde blockiert. Tippe erneut auf Anhören.":"Die Aussprache konnte nicht wiedergegeben werden.")}
function route(){stopAudio();writing.destroy();nav.classList.remove("open");const path=(location.hash.slice(1)||"/").split("?")[0];document.querySelectorAll("nav a").forEach(a=>a.toggleAttribute("aria-current",a.hash.slice(1)===path));if(path==="/")home();else if(path==="/learn"||path==="/review")startSession(path.slice(1));else if(path==="/write")writeView();else if(path==="/vocabulary")vocabulary();else if(path.startsWith("/word/"))detail(path.split("/").pop());else if(path==="/progress")progressView();else if(path==="/settings")settingsView();else if(path==="/sources")sources();else home();window.scrollTo(0,0)}
function home(){const s=summary(),due=dueItems().length,fresh=newItems().length,lesson=currentLesson();app.innerHTML=`<section class="hero"><div class="panel"><p class="eyebrow">${lesson?esc(lesson.title):"Kurs abgeschlossen"}</p><h1>${lesson?esc(lesson.canDo):"Alle Kursziele erreicht."}</h1><p class="muted">${lesson?esc(lesson.objective):"Wiederhole regelmäßig."}</p>${progressBar(s.started,state.vocabulary.length,"Begonnener Wortschatz")}<p>${s.started} von ${state.vocabulary.length} Wörtern begonnen</p><div class="actions">${button("Weiterlernen","#/learn")}${button(`Wiederholen (${due})`,"#/review","secondary")}${button("Schreiben üben","#/write","secondary")}</div></div><aside class="panel"><h2>Heute</h2><div class="stats"><div class="stat"><strong>${due}</strong>fällig</div><div class="stat"><strong>${fresh}</strong>neu</div><div class="stat"><strong>${s.learned}</strong>abrufbar</div><div class="stat"><strong>${s.mature}</strong>gefestigt</div></div></aside></section><section class="lesson-list"><h2>Lernweg</h2>${state.lessons.map(lessonCard).join("")}</section><section class="actions">${button("Wortschatz","#/vocabulary","secondary")}${button("Fortschritt","#/progress","secondary")}${button("Quellen & Lizenzen","#/sources","secondary")}</section>`}
function lessonCard(l){const open=unlockedLessons().some(x=>x.id===l.id),done=lessonMastered(l),n=l.items.filter(id=>mastery(card(id))>=2).length;return`<article class="panel lesson ${open?"":"locked"}"><p class="eyebrow">${done?"✓ gemeistert":open?"Aktuell":"🔒 gesperrt"}</p><h3>${esc(l.title)}</h3><p>${esc(l.canDo)}</p>${progressBar(n,l.items.length,l.title)}<small>${n}/${l.items.length} in Hören, Bedeutung und Abruf bestätigt</small></article>`}
function startSession(mode){const items=sessionItems(mode);if(!items.length){app.innerHTML=`<section class="panel"><h1>Nichts fällig</h1><p>Für heute sind alle Wiederholungen geschafft.</p>${button("Zur Startseite","#/")}</section>`;return}activeSession={mode,queue:items.map(v=>({v})),index:0,attempts:0,correct:0};renderExercise()}
function renderExercise(){const s=activeSession;if(s.index>=s.queue.length){app.innerHTML=`<section class="panel"><p class="eyebrow">Sitzung beendet</p><h1>Aktiv geübt</h1><div class="stats"><div class="stat"><strong>${s.attempts}</strong>Abrufe</div><div class="stat"><strong>${s.correct}</strong>korrekt</div></div><p>Fehlerhafte Wörter wurden in dieser Sitzung erneut abgefragt.</p><div class="actions">${button("Zur Startseite","#/")}${button("Noch einmal wiederholen","#/review","secondary")}</div></section>`;return}const v=s.queue[s.index].v,c=card(v.id);s.current=v;s.answered=false;if(!c.seen&&!c.n){introduce(v.id);s.queue.splice(Math.min(s.queue.length,s.index+3),0,{v,retrieval:true});return renderIntro(v)}const skill=weakestSkill(c),type=exerciseType(c,skill);s.skill=skill;s.type=type;if(type==="meaning")renderTypedMeaning(v);else if(type==="production")renderProduction(v);else if(type==="tone")renderTone(v);else if(type==="sentence")renderSentence(v);else renderListening(v)}
function weakestSkill(c){return["meaning","production","listening"].sort((a,b)=>c.skills[a]-c.skills[b])[0]}
function exerciseType(c,skill){if(Math.min(c.skills.meaning,c.skills.production,c.skills.listening)>=2&&c.n%4===3)return"sentence";if(skill==="listening")return c.n%2?"tone":"listening";return skill}
function header(label){const s=activeSession;return`<p class="eyebrow">${label} · ${s.index+1}/${s.queue.length}</p>${progressBar(s.index,s.queue.length)}`}
function pinyin(v,where){const show=where==="intro"||state.settings.pinyin==="immer"||(state.settings.pinyin==="progressiv"&&card(v.id).s<3)||where==="answer";return show?`<div class="pinyin">${v.pinyin}</div>`:""}
function renderIntro(v){app.innerHTML=`<section class="card learn-card">${header("Neues Wort")}<div class="hanzi" lang="zh-Hans">${v.simplified}</div>${pinyin(v,"intro")}<div class="meaning">${esc(v.shortGerman)}</div><button data-audio="${v.simplified}">▶ Aussprache</button><p>${esc(v.noteGerman)}</p>${example(v)}<div class="feedback"><strong>Merke:</strong> Gleich musst du das Wort selbst abrufen.</div><div class="actions"><button data-continue>Weiter</button></div></section>`;if(state.settings.autoAudio)playChinese(v.simplified)}
function renderTypedMeaning(v){app.innerHTML=`<section class="card learn-card">${header("Bedeutung aktiv abrufen")}<div class="hanzi" lang="zh-Hans">${v.simplified}</div>${pinyin(v,"question")}<form data-response="meaning"><label for="response">Was bedeutet das?</label><input name="response" id="response" class="response" autocomplete="off" required><button>Prüfen</button></form><div id="feedback" aria-live="polite"></div></section>`;requestAnimationFrame(()=>document.querySelector("#response")?.focus())}
function renderProduction(v){app.innerHTML=`<section class="card learn-card">${header("Chinesisch aktiv abrufen")}<div class="meaning">${esc(v.shortGerman)}</div><p>Sprich die Form zuerst und gib danach Hanzi, Pinyin mit Tonzeichen oder nummeriertes Pinyin ein.</p><form data-response="production"><label for="response">Chinesische Form</label><input name="response" id="response" class="response" autocomplete="off" required><button>Prüfen</button></form><div id="feedback" aria-live="polite"></div></section>`;requestAnimationFrame(()=>document.querySelector("#response")?.focus())}
function renderListening(v){const answers=choices(v,"semantic");app.innerHTML=`<section class="card learn-card">${header("Hörverstehen")}<p class="prompt">Höre zu. Welche Bedeutung passt?</p><button data-audio="${v.simplified}">▶ Noch einmal anhören</button><div class="answer-grid">${answers.map(a=>`<button class="answer" data-answer="${a.id}">${esc(a.shortGerman)}</button>`).join("")}</div><div id="feedback" aria-live="polite"></div></section>`;playChinese(v.simplified)}
function renderTone(v){const opts=toneChoices(v);app.innerHTML=`<section class="card learn-card">${header("Töne unterscheiden")}<p class="prompt">Höre zu. Welche Aussprache passt?</p><button data-audio="${v.simplified}">▶ Noch einmal anhören</button><div class="answer-grid">${opts.map(x=>`<button class="answer" data-tone="${esc(x)}">${esc(x)}</button>`).join("")}</div><div id="feedback" aria-live="polite"></div></section>`;playChinese(v.simplified)}
function renderSentence(v){const ex=v.examples[0],blank=ex.zh.includes(v.simplified)?ex.zh.replace(v.simplified,"＿＿"):"＿＿";app.innerHTML=`<section class="card learn-card">${header("Im Satz anwenden")}<p class="sentence" lang="zh-Hans">${blank}</p><p>${esc(ex.de)}</p><div class="answer-grid">${choices(v,"form").map(a=>`<button class="answer" data-answer="${a.id}">${a.simplified}</button>`).join("")}</div><div id="feedback" aria-live="polite"></div></section>`}
function choices(v,kind){const c=card(v.id),known=new Set([...Object.keys(state.progress.c),...unlockedLessons().flatMap(l=>l.items)]),pool=state.vocabulary.filter(x=>x.id!==v.id&&known.has(x.id));pool.sort((a,b)=>(c.confusions[b.id]||0)-(c.confusions[a.id]||0)+similarity(v,b,kind)-similarity(v,a,kind));return shuffle([v,...pool.slice(0,3)])}
function similarity(a,b,kind){let n=0;if(a.tags.some(t=>b.tags.includes(t)))n+=3;if(a.partOfSpeech===b.partOfSpeech)n+=2;if(kind==="form"&&a.simplified.length===b.simplified.length)n+=2;if(a.pinyin.split(" ").length===b.pinyin.split(" ").length)n++;return n}
function shuffle(xs){return xs.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function toneChoices(v){const plain=s=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,""),base=plain(v.pinyin),tones={a:"āáǎà",e:"ēéěè",i:"īíǐì",o:"ōóǒò",u:"ūúǔù",ü:"ǖǘǚǜ"},variants=[v.pinyin];for(let i=0;i<4;i++)variants.push([...base].map(ch=>tones[ch]?.[i]||ch).join(""));return shuffle([v.pinyin,...new Set(variants.filter(x=>x!==v.pinyin))].slice(0,4))}
function answer(id,el){finishChoice(id===activeSession.current.id,el,id)}
function toneAnswer(value,el){finishChoice(value===activeSession.current.pinyin,el,value)}
function finishChoice(good,el,chosen){if(activeSession.answered)return;activeSession.answered=true;el.classList.add(good?"correct":"wrong");app.querySelectorAll("[data-answer],[data-tone]").forEach(b=>b.disabled=true);recordResult(good,chosen);showFeedback(good)}
function showFeedback(good,ratePronunciation=false){const v=activeSession.current,f=document.querySelector("#feedback");f.innerHTML=`<div class="feedback"><strong>${good?"✓ Richtig.":"✕ Noch nicht sicher."}</strong><p><span lang="zh-Hans">${v.simplified}</span></p>${pinyin(v,"answer")}<p>${esc(v.shortGerman)} · ${esc(v.noteGerman)}</p>${example(v)}<button data-audio="${v.simplified}">▶ Anhören und nachsprechen</button>${ratePronunciation?`<p>Vergleiche deine Aussprache ehrlich mit der Wiedergabe.</p><div class="rating"><button data-pronunciation="again">Noch üben</button><button data-pronunciation="good" class="secondary">Klang passend</button></div>`:`<div class="actions"><button data-next data-result="${good?"good":"again"}">Weiter</button></div>`}</div>`}
const EXAMPLE_GLOSSES={"学生":["xuésheng","Schüler/in"],"老师":["lǎoshī","Lehrer/in"],"德国":["Déguó","Deutschland"],"中国":["Zhōngguó","China"],"茶":["chá","Tee"],"很":["hěn","sehr; Bindewort vor Adjektiven"],"吗":["ma","Fragepartikel"],"个":["ge","allgemeines Zähleinheitswort"],"喝":["hē","trinken"],"没":["méi","nicht haben / nicht vorhanden"],"都":["dōu","alle"],"写":["xiě","schreiben"]};
function example(v){const ex=v.examples[0],explicit=ex.glosses||[],automatic=Object.entries(EXAMPLE_GLOSSES).filter(([text])=>ex.zh.includes(text)&&!v.simplified.includes(text)).map(([text,[pinyin,de]])=>({text,pinyin,de})),all=[...explicit,...automatic].filter((g,i,a)=>a.findIndex(x=>x.text===g.text)===i),glosses=all.map(g=>`<button class="gloss" type="button" title="${esc(g.pinyin)} · ${esc(g.de)}" aria-label="${esc(g.text)}: ${esc(g.pinyin)}, ${esc(g.de)}">${esc(g.text)}</button>`).join(" ");return`<div class="example"><strong lang="zh-Hans">${ex.zh}</strong><br>${ex.pinyin}<br>${esc(ex.de)}${glosses?`<p class="meta">Noch nicht gelernt: ${glosses}</p>`:""}</div>`}
function recordResult(good,chosen=""){const s=activeSession;s.attempts++;if(good)s.correct++;recordSkill(s.current.id,s.skill,good,good?"":chosen);if(!good)s.queue.splice(Math.min(s.queue.length,s.index+3),0,{v:s.current,retry:true})}
function advance(rating){rate(activeSession.current.id,rating);activeSession.index++;renderExercise()}
function submit(e){const kind=e.target.dataset.response;if(!kind)return;e.preventDefault();if(activeSession.answered)return;const value=new FormData(e.target).get("response")||"",good=kind==="meaning"?acceptedMeaning(activeSession.current,value):acceptedProduction(activeSession.current,value);activeSession.answered=true;activeSession.baseResult=good;e.target.querySelectorAll("input,button").forEach(x=>x.disabled=true);recordResult(good,value);showFeedback(good,kind==="production")}
function acceptedMeaning(v,value){const norm=s=>s.toLowerCase().trim().replace(/[!?.,;…]/g,"").replace(/\b(der|die|das|ein|eine)\b/g,"").replace(/\s+/g," ").trim();return v.german.some(x=>norm(value)===norm(x))||norm(v.shortGerman).split(/\s*[\/;]\s*/).includes(norm(value))}
function acceptedProduction(v,value){const norm=s=>s.toLowerCase().replace(/[\s'’.-]/g,"").normalize("NFC");return[norm(v.simplified),norm(v.traditional),norm(v.pinyin),norm(v.pinyinNumbered)].includes(norm(value))}
function pronunciationRate(r){recordSkill(activeSession.current.id,"pronunciation",r==="good");advance(activeSession.baseResult?(r==="good"?"good":"hard"):"again")}
function vocabulary(query=""){const q=query.trim().toLowerCase(),items=state.vocabulary.filter(v=>!q||[v.simplified,v.traditional,v.pinyin,v.shortGerman].join(" ").toLowerCase().includes(q));app.innerHTML=`<section><p class="eyebrow">Alle Einträge</p><h1>Wortschatz</h1><input class="search" id="vocab-search" type="search" placeholder="Chinesisch, Pinyin oder Deutsch suchen" value="${esc(query)}"><div class="list" id="vocab-list">${vocabRows(items)}</div></section>`}
function vocabRows(items){return items.map(v=>`<a class="vocab-row" href="#/word/${v.id}"><span class="zh" lang="zh-Hans">${v.simplified}</span><span>${v.pinyin}</span><span class="de">${esc(v.shortGerman)}</span><span class="meta">${mastery(card(v.id))}/9</span></a>`).join("")||"<p>Keine Treffer.</p>"}
function detail(id){const v=state.vocabulary.find(x=>x.id===id);if(!v)return home();app.innerHTML=`<article class="panel"><p class="eyebrow">Wortdetails · Gesamtkompetenz ${mastery(card(id))}/9</p><div class="hanzi" lang="zh-Hans">${v.simplified}</div>${pinyin(v,"answer")}<h1>${esc(v.shortGerman)}</h1><button data-audio="${v.simplified}">▶ Aussprache</button><h2>Bedeutung und Gebrauch</h2><p>${esc(v.noteGerman)}</p><p class="meta">${esc(v.partOfSpeech)}</p><h2>Beispiel</h2>${example(v)}<h2>Zeichen</h2><p>${v.characters.map(c=>`<a class="button secondary" href="#/write?char=${encodeURIComponent(c)}">${c}</a>`).join(" ")}</p></article>`}
function writeView(){const requested=new URLSearchParams(location.hash.split("?")[1]||"").get("char"),allowed=new Set(unlockedLessons().flatMap(l=>l.items)),items=state.vocabulary.filter(v=>v.characters.length&&allowed.has(v.id));if(requested){const i=items.findIndex(v=>v.characters.includes(requested));if(i>=0)writeIndex=i}const v=items[writeIndex%items.length],char=requested||v.characters[0];app.innerHTML=`<section><p class="eyebrow">Schreiben üben</p><h1><span lang="zh-Hans">${char}</span> · ${esc(v.shortGerman)}</h1><div class="tabs"><button data-write-mode="watch" aria-selected="${writeMode==="watch"}">Ansehen</button><button data-write-mode="trace" aria-selected="${writeMode==="trace"}">Nachzeichnen</button><button data-write-mode="memory" aria-selected="${writeMode==="memory"}">Aus dem Gedächtnis</button></div><div class="writing-layout"><div class="writer-box"><div id="writer" class="writer-target"></div></div><div class="panel"><h2 id="write-status">${writeMode==="watch"?"Strichfolge ansehen":"Schreibe aus dem Gedächtnis."}</h2><p>Übe erst mit Kontur und rufe das Zeichen danach ohne Vorlage ab.</p><div class="actions"><button data-write-action="restart">Neu beginnen</button><button data-write-action="hint" class="secondary">Hinweis</button><button data-write-action="next" class="secondary">Nächstes Zeichen</button></div></div></div></section>`;requestAnimationFrame(()=>writing.create(document.querySelector("#writer"),char,writeMode,{mistake:()=>document.querySelector("#write-status").textContent="Achte auf Richtung und Lage.",stroke:d=>document.querySelector("#write-status").textContent=`Richtig: Strich ${d.strokeNum+1}.`,complete:()=>{document.querySelector("#write-status").textContent="✓ Vollständig geschrieben.";const c=card(v.id);update(v.id,{w:c.w+1,skills:{...c.skills,writing:Math.min(9,c.skills.writing+1)}})}}))}
function progressView(){const s=summary(),cards=Object.keys(state.progress.c).map(card),avg=skill=>cards.length?Math.round(cards.reduce((n,c)=>n+c.skills[skill],0)/cards.length*10)/10:0;app.innerHTML=`<section><p class="eyebrow">Dein Lernstand</p><h1>Fortschritt nach Kompetenz</h1><div class="stats"><div class="stat"><strong>${s.started}/${state.vocabulary.length}</strong>begonnen</div><div class="stat"><strong>${s.learned}</strong>aktiv abrufbar</div><div class="stat"><strong>${s.mature}</strong>gefestigt</div><div class="stat"><strong>${s.due}</strong>heute fällig</div></div><section class="panel competency"><h2>Kompetenzprofil</h2>${["meaning","production","listening","pronunciation","writing"].map(k=>`<div><span>${{meaning:"Bedeutung",production:"Aktiver Abruf",listening:"Hören",pronunciation:"Aussprache",writing:"Schreiben"}[k]}</span>${progressBar(avg(k),9,k)}<strong>${avg(k)}/9</strong></div>`).join("")}</section><p class="muted">Ein Wort gilt erst als abrufbar, wenn Bedeutung, aktiver Abruf und Hören jeweils mehrfach gelungen sind. Aussprache ist eine ehrliche Selbsteinschätzung.</p></section>`}
function settingsView(){app.innerHTML=`<section class="panel"><p class="eyebrow">Persönliche Auswahl</p><h1>Einstellungen</h1><form class="settings-form" id="settings"><label class="field"><span>Aussprache aktivieren</span><input name="audio" type="checkbox" ${state.settings.audio?"checked":""}></label><label class="field"><span>Neue Wörter automatisch vorsprechen</span><input name="autoAudio" type="checkbox" ${state.settings.autoAudio?"checked":""}></label><label class="field"><span>Pinyin</span><select name="pinyin"><option value="progressiv" ${state.settings.pinyin==="progressiv"?"selected":""}>Mit wachsender Sicherheit ausblenden</option><option value="immer" ${state.settings.pinyin==="immer"?"selected":""}>Immer zeigen</option><option value="antwort" ${state.settings.pinyin==="antwort"?"selected":""}>Erst nach der Antwort</option></select></label><label class="field"><span>Neue Wörter pro Tag</span><input name="dailyNew" type="number" min="1" max="20" value="${state.settings.dailyNew}"></label></form><h2>Sicherung</h2><div class="actions"><button data-export>Fortschritt exportieren</button><label class="button secondary">Fortschritt importieren<input id="import" type="file" accept="application/json" hidden></label><button data-reset class="danger">Fortschritt zurücksetzen</button></div>${!audioAvailable()?'<p class="feedback">Auf diesem Gerät ist keine chinesische Sprachausgabe verfügbar.</p>':""}<p class="meta">Die Aussprache nutzt die chinesische Stimme des Geräts. Höre zusätzlich regelmäßig Muttersprachlern zu.</p></section>`}
function sources(){app.innerHTML=`<article class="panel"><p class="eyebrow">Transparenz</p><h1>Quellen & Lizenzen</h1><p>Datensatzversion 2026-08-23 · App-Version 2.0.0</p><ul class="source-list"><li><strong>HanDeDict</strong> – deutsche Kernbedeutungen.</li><li><strong>CC-CEDICT</strong> – Schriftform, Pinyin und Bedeutungsumfang.</li><li><strong>Hanzi Writer</strong> – Strichfolge und Schreibquiz.</li></ul><p>Aussprache wird lokal durch die chinesische Systemstimme synthetisiert und ist keine kuratierte Muttersprachleraufnahme.</p><p>Vollständige Hinweise stehen in <a href="LICENSES.md">LICENSES.md</a>.</p></article>`}
function click(e){const b=e.target.closest("button");if(!b)return;if(b.dataset.audio)playChinese(b.dataset.audio);else if(b.dataset.answer)answer(b.dataset.answer,b);else if(b.dataset.tone)toneAnswer(b.dataset.tone,b);else if(b.hasAttribute("data-continue")){activeSession.index++;renderExercise()}else if(b.hasAttribute("data-next"))advance(b.dataset.result);else if(b.dataset.pronunciation)pronunciationRate(b.dataset.pronunciation);else if(b.dataset.writeMode){writeMode=b.dataset.writeMode;writeView()}else if(b.dataset.writeAction==="restart")writeView();else if(b.dataset.writeAction==="hint")writing.hint();else if(b.dataset.writeAction==="next"){writeIndex++;location.hash="#/write";writeView()}else if(b.hasAttribute("data-export")){const blob=new Blob([JSON.stringify(exportData(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`chinesisch-fortschritt-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}else if(b.hasAttribute("data-reset")&&confirm("Den gesamten Lernfortschritt wirklich zurücksetzen?")){reset();notify("Fortschritt zurückgesetzt.");settingsView()}}
function input(e){if(e.target.id==="vocab-search")document.querySelector("#vocab-list").innerHTML=vocabRows(state.vocabulary.filter(v=>[v.simplified,v.traditional,v.pinyin,v.shortGerman].join(" ").toLowerCase().includes(e.target.value.toLowerCase())))}
async function change(e){if(e.target.closest("#settings")){const f=new FormData(e.target.form);state.settings.audio=f.has("audio");state.settings.autoAudio=f.has("autoAudio");state.settings.pinyin=f.get("pinyin");state.settings.dailyNew=Math.max(1,Math.min(20,Number(f.get("dailyNew"))||5));saveSettings();notify("Einstellungen gespeichert.")}if(e.target.id==="import"&&e.target.files[0])try{importData(JSON.parse(await e.target.files[0].text()));notify("Fortschritt importiert.");settingsView()}catch(err){notify(`Import fehlgeschlagen: ${err.message}`)}}
boot();
