import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import{state}from"../js/state.js";
import{card,introduce,today}from"../js/progress.js";
import{unlockedLessons,newItems,practiceItems,sessionItems,lessonMastered,lessonReady,rate,dueItems}from"../js/scheduler.js";
globalThis.document={cookie:""};globalThis.location={protocol:"http:"};
const realNow=Date.now;
let now=new Date(2026,8,7,12).getTime();
const RealDate=Date;
globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[now]))}static now(){return now}};
const load=async p=>JSON.parse(await readFile(new URL(`../${p}`,import.meta.url)));
state.vocabulary=(await load("data/course.json")).items;
state.lessons=await load("data/lessons.json");
state.settings.dailyNew=5;state.progress={v:1,c:{}};
assert.equal(unlockedLessons().length,state.lessons.length);
assert.deepEqual(newItems().map(x=>x.id),["v0001","v0002","v0003","v0004","v0005"]);
// Continue through the entire course on one day, without mastery gates or repeated batches.
const introduced=new Set();
while(newItems().length){for(const v of sessionItems("new")){assert(!introduced.has(v.id));introduced.add(v.id);introduce(v.id);rate(v.id,"good")}}
assert.equal(introduced.size,state.vocabulary.length);
assert.equal(sessionItems("learn").length,0,"No automatic loop into early practice");
assert.equal(sessionItems("new").length,0);
assert(!lessonReady(state.lessons[0]));
assert(practiceItems().length>0);
const first=practiceItems()[0].id;now+=1000;rate(first,"good");assert(!practiceItems().some(v=>v.id===first),"Free practice rotates through known words");
assert.equal(card(first).d,today()+1);
for(let i=0;i<10;i++)rate(first,"easy");
assert.equal(card(first).i,0,"Same-day successes cannot inflate intervals");
assert.equal(dueItems().length,0);
now+=864e5;
assert.equal(dueItems().length,state.vocabulary.length);
rate(first,"good");assert.equal(card(first).d,today()+2);
const due=card(first).d;now+=864e5;rate(first,"easy");assert.equal(card(first).d,due,"Early practice keeps scheduled review");
rate(first,"again");assert.equal(card(first).d,today()+1);assert.equal(card(first).i,0);
rate(first,"good");assert.equal(card(first).d,today()+1,"Retry does not erase tomorrow's review");
state.progress={v:1,c:{}};introduce(first);assert(dueItems().some(v=>v.id===first),"Interrupted introductions stay due");
for(const id of state.lessons[0].items)state.progress.c[id]={s:3,n:3,skills:{meaning:2,production:2,listening:2},skillDays:{meaning:[1,2],production:[1,2],listening:[1,2]}};
assert(lessonReady(state.lessons[0]));assert(!lessonMastered(state.lessons[0]));
state.progress.lessons={"lesson-001":{passed:true,day:2}};assert(lessonMastered(state.lessons[0]));
globalThis.Date=RealDate;Date.now=realNow;
console.log("OK: Flexible portions, day-based reviews, retries, rotation and mastery.");
