import assert from "node:assert/strict";
import {state} from "../js/state.js";
import {writingCard,writingAttempt,writingReview,writingQueue,writingStrokes,today,loadProgress,exportData,importData,validate,reset} from "../js/progress.js";
const cookies=new Map();
globalThis.location={protocol:"http:"};
globalThis.document={get cookie(){return [...cookies].map(([k,v])=>k+"="+v).join("; ")},set cookie(s){const [pair]=s.split(";"),i=pair.indexOf("=");cookies.set(pair.slice(0,i),pair.slice(i+1))}};
const attempt=writingAttempt("你","memory");
attempt({mistakes:2});
state.progress={v:1,c:{}};loadProgress();
assert.equal(writingCard("你").memory[0].mistakes,2,"Mistakes survive reload before completion");
assert.equal(writingCard("你").memory[0].complete,false);
const clean=writingAttempt("你","memory");clean({complete:true});
assert.equal(writingCard("你").memory.length,2);
assert.equal(writingCard("你").memory[1].mistakes,0);
writingAttempt("你","trace")({hints:1,complete:true});
assert.equal(writingCard("你").trace[0].hints,1);
assert.throws(()=>writingAttempt("你","watch"));
const backup=JSON.parse(JSON.stringify(exportData()));reset();importData(backup);
assert.equal(writingCard("你").memory.length,2);
for(let i=0;i<35;i++)writingAttempt("你","memory")({complete:true});
assert.equal(writingCard("你").memory.length,30);
backup.progress.writing["你"].memory[0].mistakes=-1;
assert.throws(()=>validate(backup));
reset();assert.equal(writingCard("你").memory.length,0);
const day=today();
writingAttempt("你","memory")({complete:true});
assert.deepEqual(writingReview("你"),{due:day+1,stage:0,last:day});
writingAttempt("你","memory")({complete:true});
assert.equal(writingReview("你").due,day+1,"Same-day success must not extend interval");
state.progress.writing["你"].review={due:day,stage:0,last:day-1};
writingAttempt("你","memory")({complete:true});
assert.equal(writingReview("你").due,day+2,"Due success advances interval");
state.progress.writing["你"].review={due:day+5,stage:3,last:day-2};
writingAttempt("你","memory")({complete:true});
assert.equal(writingReview("你").due,day+5,"Early practice preserves schedule");
const failed=writingAttempt("你","memory");
failed({mistakes:3,strokes:{0:2,2:1}});
assert.equal(writingReview("你").due,day,"Interrupted practice stays due");
failed({complete:true});
assert.deepEqual(writingReview("你"),{due:day+1,stage:0,last:day});
failed({complete:true});
assert.equal(writingCard("你").memory.length,5,"Duplicate completion does not add attempts");
writingAttempt("你","trace")({complete:true,mistakes:2,strokes:{1:2}});
assert.equal(writingReview("你").due,day+1,"Tracing does not change memory schedule");
assert.deepEqual(writingStrokes("你","memory"),[{stroke:0,count:2},{stroke:2,count:1}]);
assert.deepEqual(writingStrokes("你","trace"),[{stroke:1,count:2}]);
writingAttempt("我","memory")({mistakes:1});
assert.deepEqual(writingQueue(["新","你","我"]),["我","新"],"Due characters precede new characters; future reviews excluded");
const saved=JSON.parse(JSON.stringify(exportData()));
reset();importData(saved);loadProgress();
assert.equal(writingStrokes("你","memory")[0].count,2);
assert.equal(writingReview("你").due,day+1);
saved.progress.writing["你"].memory[0].strokes={bad:1};
assert.throws(()=>validate(saved));
reset();
console.log("OK: Writing persistence, modes, backup, validation and reset.");
